### ISSUE TITLE
add social media link icons in the footer component

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#11]

**Comment by k-deepak04** [comment]
@gbowne1 i forked this repo and write the cmd - npm install.
and then started this by using npm start.
This type of ui i can see. can you please cnfrm it?

![image](https://user-images.githubusercontent.com/96341431/232618008-bada694f-f967-4e57-9b11-81de464ac5a0.png)

**Comment by k-deepak04** [comment]
if the problem is in my installation. i will delete this one and again fork it.

**Comment by gbowne1** [comment]
Yeah @k-deepak04 

Thats how it currently looks.  I was contemplating redoing it completely.  But I think it can be fixed.  It is a complete mess of files, etc.

This is not how I meant it to look, though.

**Comment by k-deepak04** [comment]
@gbowne1 okay . I'll try to clear this mess

**Comment by gbowne1** [comment]
One clue, the black bar must be at the top.  That's the navbar.
