### ISSUE TITLE
Add hover effect and redesign the footer page

### ISSUE THREAD

**Issue by k-deepak04** [gbowne1/gbowne1site_react#14]
@gbowne1 i'm adding this issue and creating a new pr for this.

**Comment by gbowne1** [comment]
Cool thanks @k-deepak04 

! yeah I meant to do that.  Waited till the issues were fixed.  I have some special things that need to go into the footer.

**Comment by gbowne1** [comment]
I added design to the last PR comment  and als9 in discussion.
