### ISSUE TITLE
Fix Alignment of Navbar Ui 

### ISSUE THREAD

**Issue by k-deepak04** [gbowne1/gbowne1site_react#17]
tabs and links should be aligned to the left. there must be space between them

**Comment by dz-ai** [comment]
Hi can I go for it?

**Comment by gbowne1** [comment]
Sure @dz-ai

**Comment by gbowne1** [comment]
Ok :+1:

**Comment by dz-ai** [comment]
If you want I can move the search field to the right so it may look better.
<img width="1280" alt="Screen Shot 2023-04-19 at 12 09 12" src="https://user-images.githubusercontent.com/82286961/233027091-95aa020e-ace4-48f1-9079-af7286ced347.png">

**Comment by gbowne1** [comment]
No am putting a Login/Logout button there. @dz-ai
