### ISSUE TITLE
Redesign Contact Me.

### ISSUE THREAD

**Issue by k-deepak04** [gbowne1/gbowne1site_react#19]
Design the Contact me as per the Screenshots mentioned in the Discussion tabs.

**Comment by gbowne1** [comment]
@k-deepak04 

My social links are:

https://www.instagram.com/gbowne1/
https://www.reddit.com/user/gbowne1
https://www.facebook.com/gbowne1/
https://www.youtube.com/@gbowne1
https://www.twitch.tv/gbowne1
https://github.com/gbowne1
https://www.linkedin.com/in/gregory-bowne-47886591/
https://twitter.com/gbowne1

**Comment by k-deepak04** [comment]
#22 done

**Comment by k-deepak04** [comment]
#25 done
