### ISSUE TITLE
Fix favicon not loading

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#3]
The correct favicon.ico is not loading even in a build.

I removed the default one by CRA and made sure its in the public folder but its not loading. 

The correct file is 16x16 and shows the GKB logo.

**Comment by sharatkatwa** [comment]
To fix this issue change the filename 
favico.ico to  favicon.ico

**Comment by gbowne1** [comment]
@sharatkatwa 

I tried that.  I think the file is actually empty, as .ico files should render normally. Aparently you can just rename .png to .ico

I made a copy of the favicon-16x16 .png from the src/assets folder and renamed it as the .ico file inside /public  Still won't work.

I may try again though.

**Comment by sharatkatwa** [comment]
I don't know how to run this react app 
npm install is giving lot of errors

**Comment by gbowne1** [comment]
npm start will do it @sharatkatwa

**Comment by agengwibowoo** [comment]
I think the problem is with your `favico.ico` file
I changed the file into png or another .ico file then it's working normally

**Comment by gbowne1** [comment]
I also think its a problem with the file itself.  I tried re-naming it.  It did mont work no matter what name I gave it, even the correct favicon.ico name.  So you are lileky right @agengwibowoo 

I have not chosen what to replace the logo.svg with either
