### ISSUE TITLE
Add some of the text from my GitHub Profile

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#33]
I intend to change a large portion of my GitHub profile README.MD by moving most of the text in my Readme Profile on GitHub to the About Me section of my page then  just link to my page in my readme and provide a short readme instead so that my GitHub profile is complete but not TL:DR.   People can go to my site if they want to know more about me.

**Comment by sergomen** [comment]
Can you assign to me?

**Comment by gbowne1** [comment]
Fixed in #60 and #59.
