### ISSUE TITLE
[BUG] Top Nav bar issues

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#34]
There are several issues with the blue top nav bar.

- Too high, should be 60px-80px high on desktop.
- Navigation and its link buttons are now invisible 
- Search bar also the wrong size

Other minor issues.

**Comment by gbowne1** [comment]
This is how it should look.. and did for a while till it got messed up.

![gbowne1_navbar](https://github.com/gbowne1/gbowne1site_react/assets/47549872/84f960e7-9c90-46e8-8520-ff6e38e4ea73)

**Comment by gbowne1** [comment]
@adeleke5140

**Comment by adeleke5140** [comment]
thank you for the pointer @gbowne1.

I fixed all the `a11y` issues and tested with the Google lighthouse automated testing tool. I will send a PR you can review in 5min.

**Comment by gbowne1** [comment]
No rush.

If you want to work on other issues you are welcome to.

CodeBooker
reactsocialnetwork 

Also few of my other projects need a11y work as well

**Comment by adeleke5140** [comment]
Great. I would take a look at them as well.

**Comment by gbowne1** [comment]
Great. I welcome both new filed issues and PR's.  Keep in mind that it will take a minimum of 2 reviews to get a PR merged on codebooker repo, but that shouldn't be an issue.  5 successful merges and you will be invited to be collaborator.

**Comment by gbowne1** [comment]
@adeleke5140 make sure you sync this repo.  I pushed up a change that fixed an issue or two.
 
 I did the Firefox accessibility tests tonight..  Still missing Clickable element Focus Styling / Keyboard on the Navbar Buttons and the Search bar

**Comment by adeleke5140** [comment]
Got it. I am working on this right now.
