### ISSUE TITLE
[BUG] Footer Social Icons

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#35]
The footer social icons no longer have their styling and colorization.

The links appear to be fine and working.

**Comment by adeleke5140** [comment]
I want to solve this next.

What styling and colorization should the icons have?

**Comment by gbowne1** [comment]
@adeleke5140 

See <https://user-images.githubusercontent.com/47549872/232705889-4d3e2950-f2b2-4ee2-946a-4240ca0ea5ed.png>

**Comment by gbowne1** [comment]
You might as well fix https://github.com/gbowne1/gbowne1site_react/issues/42 at the same time.
