### ISSUE TITLE
[BUG] Blog not displaying

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#36]
Clicking on the blog button in the nav, if you can hover find it with the hand on the nav bar.

The page as it exists doesn t display.

**Comment by gbowne1** [comment]
Not sure about the blog page.

**Comment by JiginJayaprakash** [comment]
@gbowne1  I would like to work on it , Can you please assign it me ?

**Comment by gbowne1** [comment]
Ok @JiginJayaprakash I will assign you
