### ISSUE TITLE
[TODO] Fix the footer

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#42]
The footer has a number of issues..

The app backround is too light to tell any significant issue. The footer background is white, but has gray bars across the icons and the copyright section.

The social media icons somehow lost their colorization #35 and I would like to use the icons' official colorization, and the Instagram icon should use the same colorization it uses on their site/app.

I also feel like the footer especially is way too tall, and the icons do not have good separation, especially if someone looked at it on a mobile device and tried fat fingering it with big fingers. Clicking on Desktop view would be fine but, on mobile would be not that good.

Separate and a minor issue is that there is ~5-10px of margin/padding on the left side of the view all the way down.. that also affects the footer.

**Comment by r0ld3x** [comment]
assign me.

**Comment by gbowne1** [comment]
The current footer is: 
![Screenshot 2023-10-21 at 19-35-23 React App](https://github.com/gbowne1/gbowne1site_react/assets/47549872/4fdcd42d-716d-4f9b-aa70-f9f115bdd4ed)

It's a bit wonky.  The background is messed up.  It has two extremely light gray bars going across what looks like a extremely white background, and it is so bad that the color difference is hard to see.

**Comment by adeleke5140** [comment]
Alright, I will get started with this as well.

**Comment by adeleke5140** [comment]
@gbowne1 How did the footer look like before these issues occurred? 
I would like to know so I know the appropriate change to make.

**Comment by adeleke5140** [comment]
This is the change I have made. Do you want the copyright and your social links at the centre instead?

And are you okay with the white background color?
<img width="1797" alt="Screenshot 2023-10-22 at 10 40 40" src="https://github.com/gbowne1/gbowne1site_react/assets/32024147/ce2a5583-645e-4d76-b334-0299eaa07faf">

**Comment by gbowne1** [comment]
Yes they should be centered.

I want to implement theme / mode toggle too for light and dark mode.

I thought about using a medium gray background for the footer so I would go with that instead of white.

The footer should be

**Comment by adeleke5140** [comment]
Alright. What is the hex value for the medium gray background?

**Comment by gbowne1** [comment]
I would think any medium gray in the #6xxxxx - #9xxxxx space would work.. perhaps something in the #7xxxxx range would work best.  https://www.youtube.com/watch?v=I2eDM1b95bU

**Comment by adeleke5140** [comment]
Oh, I assumed you had a specific hex value in mind? I am not that great with colors.

**Comment by gbowne1** [comment]
@adeleke5140 no, I don't have any specific color in mind.

**Comment by adeleke5140** [comment]
Alright. got it.
