### ISSUE TITLE
Fix Contact page

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#44]
The contact page needs fixing, the contact extends through the bottom of the footer 

![Screenshot 2023-10-22 at 18-07-48 React App](https://github.com/gbowne1/gbowne1site_react/assets/47549872/f70c1754-881d-4027-a8a0-16f007eb2d84)

The content is huge making it scroll and its not visible in its entirety and as you can see from the pic it actually goes through the bottom of the footer.

Even though my device is 1920x1080, my viewport is 1884px x 905px so use your browsers responsive test and set it to that viewport and see how it looks and behaves at that resolution.  in my viewport (and most others except mobile/phone) it should be completely visible in one view without having to scroll.

**Comment by gbowne1** [comment]
The actual content could be a bit wider too to fill up the margin

**Comment by auth-02** [comment]
@gbowne1 can you assign me this issue?

**Comment by gbowne1** [comment]
Ok @auth-02

**Comment by auth-02** [comment]
PR Raised for #48 Issue!
