### ISSUE TITLE
Migrate the App components to use functional components instead of class based components.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#53]
Most if not all of the components of the App have used class based components.

change them to use ES7+ or ES2016+ and functional components.

**Comment by JiginJayaprakash** [comment]
@gbowne1  Can I work on this, if yes , then please assign to me.Thanks

**Comment by gbowne1** [comment]
Sure, @JiginJayaprakash.  Thanks. I will assign you.
