### ISSUE TITLE
Fix navbar and routing

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#6]
My desktop device is 1920x1080 but the CSS viewport is 1884px x 905px.

I always expect my topbar/topnav on desktop to be 1884x60 when inspecting it in console.

I expect CSS breakpoints in any media queries to be:

1920x1080 (Desktops)
1366x768 (Laptops)
375x667 (Some mobile and tablet)
360x640 (Other mobile and tablet)

I expect the footer to be no more than 500px high, but my footer only needs to contain my social icons and copyright and quick contact links so can be very short in height.

My two choices for color in navbar are black or blue.

@k-deepak04

**Comment by gbowne1** [comment]
Routing should be

* {404}
/ { same as home }
/home 
/blog
/about
/contact
/gallery

**Comment by k-deepak04** [comment]
@gbowne1 i'm not at good in making the site responsive. i can add routes and design the things for you.

**Comment by gbowne1** [comment]
Once the design and layout and routing is ďone will be easy to be esponsive.  I can do that pretty easy

**Comment by k-deepak04** [comment]
@gbowne1 i don't want to commit directly in the main branch. i want to create pr's and then you can merge them.
it will be good for my profile :)
by the way i have fixed your navbar and added routes

![image](https://user-images.githubusercontent.com/96341431/232883004-c1c9d4f8-504e-4f8e-a6d3-ddcf4dae4251.png)

**Comment by gbowne1** [comment]
You can commit and PR directly only if you feel the commit will not break changes and also for only very minor changes.

**Comment by gbowne1** [comment]
Is there a PR for the appbar change?

**Comment by k-deepak04** [comment]
i'm unable to create the pr

**Comment by gbowne1** [comment]
oh ok.  I just wondered.

Yeah as a named contributor, you can still PR.  I do not mind if you push directly if it is something minor and that you are certain it won't break.

**Comment by k-deepak04** [comment]
#20 i guess i pushed the code and now the deletion and insertions are opposite in PR.
check once @gbowne1

**Comment by gbowne1** [comment]
It seems to be fine now @k-deepak04

**Comment by k-deepak04** [comment]
check again @gbowne1 i pushed again in the main file

**Comment by gbowne1** [comment]
I did get one PR which I merged.

**Comment by k-deepak04** [comment]
ok
