### ISSUE TITLE
Unable to see the CookieBar component

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/gbowne1site_react#63]
I added a CookieBar component.

I was unable to get the component to render.  

It's a semi-transparent bar with a yellowish button in a small strip at the bottom of the view.

**Comment by OluwaninsolaAO** [comment]
# CookieBar component works as expected
Hello @gbowne1, while reviewing your project, I observed that the CookieBar component is functioning as intended. If you have a specific behaviour in mind for the cookie consent, please let me know. The CookieConsent module in use handles cookie consent and ensures that the client's choice persists on the client side. However, if you wish to see the cookie consent popup for a review after responding from your browser client, you'll need to clear your client's "Cookie and site data," effectively removing all existing cookies. Upon reloading the page, you should then encounter the CookieBar component again.

I hope this information proves helpful.

![image](https://github.com/gbowne1/gbowne1site_react/assets/36889745/79c90fda-45f4-4b99-85ca-f4dba9955560)

![image](https://github.com/gbowne1/gbowne1site_react/assets/36889745/148acc40-7ae5-42c8-ac05-3725aef65cba)

![image](https://github.com/gbowne1/gbowne1site_react/assets/36889745/3d546420-ab8f-46f7-b664-91bd82ecd649)

![image](https://github.com/gbowne1/gbowne1site_react/assets/36889745/803b069f-48cc-4d23-8fee-3e7989417adb)

**Comment by gbowne1** [comment]
Ok, I will have a look at this.

Thanks @OluwaninsolaAO

**Comment by gbowne1** [comment]
Hi, @OluwaninsolaAO. I worked on this some and I was able to fix this by clearing out the entire browser cache.  Which needed to be done anyhow.  Thanks.  Closing this issue.
